#!/bin/bash
# design-cleanup.sh — Remove preview screenshots generated by design-preview.mjs
#
# Usage:
#   ./design-cleanup.sh <directory>
#
# Example:
#   ./design-cleanup.sh .planning/design/screens/dashboard/
#
# Removes:
#   - preview-mobile.png
#   - preview-tablet.png
#   - preview-desktop.png

set -euo pipefail

DIR="${1:-}"

if [ -z "$DIR" ]; then
  echo "Usage: $0 <directory>"
  echo "Removes preview-*.png files from the given directory."
  exit 1
fi

if [ ! -d "$DIR" ]; then
  echo "Directory not found: $DIR"
  exit 1
fi

COUNT=0
for file in "$DIR"/preview-*.png; do
  if [ -f "$file" ]; then
    rm "$file"
    echo "Removed: $file"
    COUNT=$((COUNT + 1))
  fi
done

if [ "$COUNT" -eq 0 ]; then
  echo "No preview screenshots found in $DIR"
else
  echo "Cleaned up $COUNT preview screenshot(s)"
fi
