// Spartan AI Toolkit — Assembler
// Builds CLAUDE.md and AGENTS.md from section files based on selected packs.

import { readFileSync, existsSync } from 'node:fs';
import { join } from 'node:path';

const ALWAYS_INCLUDE_TOP = ['00-header.md', '01-core.md'];
const ALWAYS_INCLUDE_BOTTOM = ['90-footer.md'];

/**
 * Assemble CLAUDE.md from section files.
 * @param {string} claudeMdDir - Path to the claude-md/ directory
 * @param {string[]} selectedPacks - Pack names the user picked
 * @param {object} packDefs - The PACKS object from packs.js
 * @returns {string} The full CLAUDE.md content
 */
export function assembleCLAUDEmd(claudeMdDir, selectedPacks, packDefs) {
  let parts = [];

  // Always include header + core
  for (const file of ALWAYS_INCLUDE_TOP) {
    const fp = join(claudeMdDir, file);
    if (existsSync(fp)) {
      parts.push(readFileSync(fp, 'utf-8'));
    }
  }

  // Pack-specific sections (in pack order, not random)
  const seen = new Set();
  for (const pack of selectedPacks) {
    const def = packDefs[pack];
    if (!def) continue;
    for (const section of def.claudeSections) {
      if (seen.has(section)) continue;
      seen.add(section);
      const fp = join(claudeMdDir, section);
      if (existsSync(fp)) {
        parts.push(readFileSync(fp, 'utf-8'));
      }
    }
  }

  // Always include footer
  for (const file of ALWAYS_INCLUDE_BOTTOM) {
    const fp = join(claudeMdDir, file);
    if (existsSync(fp)) {
      parts.push(readFileSync(fp, 'utf-8'));
    }
  }

  return parts.join('\n');
}

/**
 * Assemble AGENTS.md from section files + agent definitions.
 * Follows the AGENTS.md spec: Project Context, pack content, Agents, Boundaries.
 * @param {string} claudeMdDir - Path to the claude-md/ directory
 * @param {string} agentsDir - Path to the agents/ directory
 * @param {string[]} selectedPacks - Pack names the user picked
 * @param {object} packDefs - The PACKS object from packs.js
 * @returns {string} The full AGENTS.md content
 */
export function assembleAGENTSmd(claudeMdDir, agentsDir, selectedPacks, packDefs) {
  const parts = [];

  // Header
  parts.push('# AGENTS.md');
  parts.push('');
  parts.push('> Generated by [Spartan AI Toolkit](https://github.com/spartan-stratos/spartan-ai-toolkit)');
  parts.push('');

  // Project Context — pull from header if it exists
  parts.push('## Project Context');
  parts.push('');
  const headerFile = join(claudeMdDir, '00-header.md');
  if (existsSync(headerFile)) {
    const header = readFileSync(headerFile, 'utf-8');
    // Strip the top-level heading, keep the useful content
    const lines = header.split('\n');
    const contentLines = lines.filter(l => !l.startsWith('# '));
    const trimmed = contentLines.join('\n').trim();
    if (trimmed) {
      parts.push(trimmed);
      parts.push('');
    }
  }

  // Core principles — compact version
  const coreFile = join(claudeMdDir, '01-core.md');
  if (existsSync(coreFile)) {
    const core = readFileSync(coreFile, 'utf-8');
    parts.push(extractSection(core));
    parts.push('');
  }

  // Pack-specific sections
  const seen = new Set();
  for (const pack of selectedPacks) {
    const def = packDefs[pack];
    if (!def) continue;
    for (const section of def.claudeSections) {
      if (seen.has(section)) continue;
      seen.add(section);
      const fp = join(claudeMdDir, section);
      if (existsSync(fp)) {
        parts.push(extractSection(readFileSync(fp, 'utf-8')));
        parts.push('');
      }
    }
  }

  // Agents — list available agents from selected packs
  const agentFiles = gatherAgents(selectedPacks, packDefs);
  if (agentFiles.length > 0 && agentsDir) {
    parts.push('## Available Agents');
    parts.push('');
    for (const agentFile of agentFiles) {
      const fp = join(agentsDir, agentFile);
      if (!existsSync(fp)) continue;
      const content = readFileSync(fp, 'utf-8');
      const name = extractFrontmatterField(content, 'name') || agentFile.replace('.md', '');
      const desc = extractFrontmatterField(content, 'description') || '';
      const firstLine = desc.split('\n')[0].trim();
      parts.push(`- **${name}**: ${firstLine}`);
    }
    parts.push('');
  }

  // Boundaries — from footer
  const footerFile = join(claudeMdDir, '90-footer.md');
  if (existsSync(footerFile)) {
    const footer = readFileSync(footerFile, 'utf-8');
    parts.push('## Boundaries');
    parts.push('');
    // Extract the "What NOT to Do" items as NEVER rules
    const neverItems = extractListItems(footer);
    if (neverItems.length > 0) {
      parts.push('**NEVER:**');
      for (const item of neverItems) {
        parts.push(`- ${item}`);
      }
      parts.push('');
    }
  }

  return parts.join('\n').trimEnd() + '\n';
}

// ── Helpers ──────────────────────────────────────────────────────

/** Strip leading separator (---) and return the content. */
function extractSection(content) {
  return content.replace(/^\s*---\s*\n?/, '').trim();
}

/** Get deduplicated agent files from selected packs. */
function gatherAgents(selectedPacks, packDefs) {
  const seen = new Set();
  const result = [];
  for (const pack of selectedPacks) {
    const def = packDefs[pack];
    if (!def) continue;
    for (const agent of (def.agents || [])) {
      if (!seen.has(agent)) {
        seen.add(agent);
        result.push(agent);
      }
    }
  }
  return result;
}

/** Extract a YAML frontmatter field value (simple single-line). */
function extractFrontmatterField(content, field) {
  const match = content.match(new RegExp(`^${field}:\\s*(.+)$`, 'm'));
  return match ? match[1].trim().replace(/^["']|["']$/g, '') : null;
}

/** Extract list items (lines starting with -) from markdown. */
function extractListItems(content) {
  return content
    .split('\n')
    .filter(l => l.match(/^-\s+/))
    .map(l => l.replace(/^-\s+/, '').trim());
}
