#!/usr/bin/env node
// Spartan AI Toolkit — Compile YAML manifests to JSON + Bash
// Generates packs.compiled.json (for CLI) and packs.sh (for setup.sh).

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { loadManifests, detectCycles, toPacks } from '../lib/resolver.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const PACKS_DIR = join(__dirname, '..', 'packs');
const SCRIPTS_DIR = __dirname;
const JSON_OUTPUT = join(PACKS_DIR, 'packs.compiled.json');
const BASH_OUTPUT = join(SCRIPTS_DIR, 'packs.sh');

const manifests = loadManifests(PACKS_DIR);
detectCycles(manifests);
const { PACKS, PACK_ORDER } = toPacks(manifests);

// --- Write JSON ---
const compiled = { PACKS, PACK_ORDER };
writeFileSync(JSON_OUTPUT, JSON.stringify(compiled, null, 2) + '\n', 'utf-8');

// --- Write Bash ---
function toVar(name) {
  return name.replace(/-/g, '_');
}

const lines = [
  '#!/usr/bin/env bash',
  '# Auto-generated by compile-packs.js — do not edit manually.',
  '# shellcheck disable=SC2034  # Variables are used dynamically via pack_var()',
  '',
  `PACK_ORDER="${PACK_ORDER.join(' ')}"`,
  '',
];

for (const name of PACK_ORDER) {
  const p = PACKS[name];
  const v = toVar(name);
  lines.push(`PACK_DESC_${v}="${p.description}"`);
  lines.push(`PACK_HIDDEN_${v}=${p.hidden}`);
  lines.push(`PACK_COMING_SOON_${v}=${p.comingSoon}`);
  lines.push(`PACK_DEPENDS_${v}="${(p.depends || []).join(' ')}"`);
  lines.push(`PACK_COMMANDS_${v}="${(p.commands || []).join(' ')}"`);
  lines.push(`PACK_RULES_${v}="${(p.rules || []).join(' ')}"`);
  lines.push(`PACK_SKILLS_${v}="${(p.skills || []).join(' ')}"`);
  lines.push(`PACK_AGENTS_${v}="${(p.agents || []).join(' ')}"`);
  lines.push(`PACK_SCRIPTS_${v}="${(p.scripts || []).join(' ')}"`);
  lines.push(`PACK_CLAUDE_SECTIONS_${v}="${(p.claudeSections || []).join(' ')}"`);
  lines.push('');
}

lines.push(
  '# Helper: get pack variable by name',
  '# Usage: pack_var "COMMANDS" "backend-micronaut" → echoes PACK_COMMANDS_backend_micronaut',
  'pack_var() {',
  '  local prefix="$1"',
  '  local pack="$2"',
  '  local safe_pack="${pack//-/_}"',
  '  local var_name="PACK_${prefix}_${safe_pack}"',
  '  eval echo "\\${$var_name:-}"',
  '}',
  '',
  '# Helper: resolve dependencies (BFS)',
  'resolve_deps() {',
  '  local selected="$1"',
  '  local resolved="$selected"',
  '  local queue="$selected"',
  '  while [[ -n "$queue" ]]; do',
  '    local next_queue=""',
  '    for pack in $queue; do',
  '      local deps',
  '      deps=$(pack_var "DEPENDS" "$pack")',
  '      for dep in $deps; do',
  '        case " $resolved " in',
  '          *" $dep "*) ;;',
  '          *) resolved="$resolved $dep"; next_queue="$next_queue $dep" ;;',
  '        esac',
  '      done',
  '    done',
  '    queue="$next_queue"',
  '  done',
  '  # Always include core',
  '  case " $resolved " in',
  '    *" core "*) ;;',
  '    *) resolved="core $resolved" ;;',
  '  esac',
  '  echo "$resolved"',
  '}',
);

writeFileSync(BASH_OUTPUT, lines.join('\n') + '\n', 'utf-8');

console.log(`Compiled ${PACK_ORDER.length} packs → ${JSON_OUTPUT}`);
console.log(`Generated packs.sh → ${BASH_OUTPUT}`);
