#!/usr/bin/env bash
# Auto-generated by compile-packs.js — do not edit manually.
# shellcheck disable=SC2034  # Variables are used dynamically via pack_var()

PACK_ORDER="core database shared-backend backend-micronaut backend-nodejs backend-python frontend-react ux-design infrastructure project-mgmt product ops research"

PACK_DESC_core="Core workflow (always installed)"
PACK_HIDDEN_core=false
PACK_COMING_SOON_core=false
PACK_DEPENDS_core=""
PACK_COMMANDS_core="spec plan build debug onboard daily context-save magic-doc memory-consolidate update pr-ready ship-pr commit-message init-project init-rules scan-rules lint-rules careful freeze unfreeze guard sessions contribute gate-review"
PACK_RULES_core="core/NAMING_CONVENTIONS.md core/TIMEZONE.md core/SKILL_AUTHORING.md"
PACK_SKILLS_core=""
PACK_AGENTS_core="phase-reviewer.md"
PACK_SCRIPTS_core=""
PACK_CLAUDE_SECTIONS_core=""

PACK_DESC_database="Database patterns, migrations, Exposed ORM"
PACK_HIDDEN_database=true
PACK_COMING_SOON_database=false
PACK_DEPENDS_database=""
PACK_COMMANDS_database="migration"
PACK_RULES_database="database/SCHEMA.md database/ORM_AND_REPO.md database/TRANSACTIONS.md"
PACK_SKILLS_database="database-patterns database-table-creator"
PACK_AGENTS_database=""
PACK_SCRIPTS_database=""
PACK_CLAUDE_SECTIONS_database="05-database.md"

PACK_DESC_shared_backend="Shared backend architecture concepts"
PACK_HIDDEN_shared_backend=true
PACK_COMING_SOON_shared_backend=false
PACK_DEPENDS_shared_backend=""
PACK_COMMANDS_shared_backend=""
PACK_RULES_shared_backend="shared-backend/ARCHITECTURE.md"
PACK_SKILLS_shared_backend=""
PACK_AGENTS_shared_backend=""
PACK_SCRIPTS_shared_backend=""
PACK_CLAUDE_SECTIONS_shared_backend=""

PACK_DESC_backend_micronaut="Kotlin + Micronaut backend"
PACK_HIDDEN_backend_micronaut=false
PACK_COMING_SOON_backend_micronaut=false
PACK_DEPENDS_backend_micronaut="database shared-backend"
PACK_COMMANDS_backend_micronaut="kotlin-service review testcontainer"
PACK_RULES_backend_micronaut="backend-micronaut/KOTLIN.md backend-micronaut/CONTROLLERS.md backend-micronaut/SERVICES_AND_BEANS.md backend-micronaut/API_DESIGN.md backend-micronaut/RETROFIT_PLACEMENT.md backend-micronaut/BATCH_PROCESSING.md"
PACK_SKILLS_backend_micronaut="api-endpoint-creator backend-api-design kotlin-best-practices testing-strategies security-checklist"
PACK_AGENTS_backend_micronaut="micronaut-backend-expert.md solution-architect-cto.md"
PACK_SCRIPTS_backend_micronaut=""
PACK_CLAUDE_SECTIONS_backend_micronaut="11-backend-micronaut.md"

PACK_DESC_backend_nodejs="Node.js backend (coming soon)"
PACK_HIDDEN_backend_nodejs=false
PACK_COMING_SOON_backend_nodejs=true
PACK_DEPENDS_backend_nodejs="database shared-backend"
PACK_COMMANDS_backend_nodejs=""
PACK_RULES_backend_nodejs=""
PACK_SKILLS_backend_nodejs=""
PACK_AGENTS_backend_nodejs=""
PACK_SCRIPTS_backend_nodejs=""
PACK_CLAUDE_SECTIONS_backend_nodejs=""

PACK_DESC_backend_python="Python backend (coming soon)"
PACK_HIDDEN_backend_python=false
PACK_COMING_SOON_backend_python=true
PACK_DEPENDS_backend_python="database shared-backend"
PACK_COMMANDS_backend_python=""
PACK_RULES_backend_python=""
PACK_SKILLS_backend_python=""
PACK_AGENTS_backend_python=""
PACK_SCRIPTS_backend_python=""
PACK_CLAUDE_SECTIONS_backend_python=""

PACK_DESC_frontend_react="React + Next.js frontend"
PACK_HIDDEN_frontend_react=false
PACK_COMING_SOON_frontend_react=false
PACK_DEPENDS_frontend_react=""
PACK_COMMANDS_frontend_react="next-app next-feature fe-review figma-to-code e2e qa js-security"
PACK_RULES_frontend_react="frontend-react/FRONTEND.md"
PACK_SKILLS_frontend_react="browser-qa js-security-audit"
PACK_AGENTS_frontend_react=""
PACK_SCRIPTS_frontend_react=""
PACK_CLAUDE_SECTIONS_frontend_react="20-frontend-react.md"

PACK_DESC_ux_design="UX design workflow — research, define, ideate, design system, prototype, test, AI asset generation"
PACK_HIDDEN_ux_design=false
PACK_COMING_SOON_ux_design=false
PACK_DEPENDS_ux_design=""
PACK_COMMANDS_ux_design="ux"
PACK_RULES_ux_design="ux-design/DESIGN_PROCESS.md"
PACK_SKILLS_ux_design="design-intelligence design-workflow"
PACK_AGENTS_ux_design="design-critic.md ai-designer.md"
PACK_SCRIPTS_ux_design="design/ai-design.sh design/ai-image.sh design/ai-image.py design/design-preview.mjs design/design-cleanup.sh"
PACK_CLAUDE_SECTIONS_ux_design="25-ux-design.md"

PACK_DESC_infrastructure="Terraform + AWS infrastructure"
PACK_HIDDEN_infrastructure=false
PACK_COMING_SOON_infrastructure=false
PACK_DEPENDS_infrastructure=""
PACK_COMMANDS_infrastructure="tf-scaffold tf-module tf-review tf-plan tf-deploy tf-import tf-drift tf-cost tf-security"
PACK_RULES_infrastructure="infrastructure/STRUCTURE.md infrastructure/MODULES.md infrastructure/STATE_AND_BACKEND.md infrastructure/NAMING.md infrastructure/SECURITY.md infrastructure/VARIABLES.md infrastructure/PROVIDERS.md"
PACK_SKILLS_infrastructure="terraform-service-scaffold terraform-module-creator terraform-review terraform-security-audit terraform-best-practices"
PACK_AGENTS_infrastructure="infrastructure-expert.md sre-architect.md"
PACK_SCRIPTS_infrastructure=""
PACK_CLAUDE_SECTIONS_infrastructure="30-infrastructure.md"

PACK_DESC_project_mgmt="Large multi-day projects (GSD)"
PACK_HIDDEN_project_mgmt=false
PACK_COMING_SOON_project_mgmt=false
PACK_DEPENDS_project_mgmt=""
PACK_COMMANDS_project_mgmt="epic project phase workstreams gsd-upgrade forensics brownfield map-codebase team"
PACK_RULES_project_mgmt=""
PACK_SKILLS_project_mgmt=""
PACK_AGENTS_project_mgmt="team-coordinator.md"
PACK_SCRIPTS_project_mgmt=""
PACK_CLAUDE_SECTIONS_project_mgmt="30-project-mgmt.md"

PACK_DESC_product="Product thinking before building"
PACK_HIDDEN_product=false
PACK_COMING_SOON_product=false
PACK_DEPENDS_product=""
PACK_COMMANDS_product="think validate teardown interview lean-canvas brainstorm web-to-prd"
PACK_RULES_product=""
PACK_SKILLS_product="web-to-prd"
PACK_AGENTS_product=""
PACK_SCRIPTS_product=""
PACK_CLAUDE_SECTIONS_product="40-product.md"

PACK_DESC_ops="Deploy & infrastructure"
PACK_HIDDEN_ops=false
PACK_COMING_SOON_ops=false
PACK_DEPENDS_ops=""
PACK_COMMANDS_ops="deploy env-setup ops-investigate-alert ops-oncall-log"
PACK_RULES_ops=""
PACK_SKILLS_ops="ops-investigate-alert ops-oncall-log"
PACK_AGENTS_ops=""
PACK_SCRIPTS_ops=""
PACK_CLAUDE_SECTIONS_ops="50-ops.md"

PACK_DESC_research="Startup research pipeline — from idea to investor-ready"
PACK_HIDDEN_research=false
PACK_COMING_SOON_research=false
PACK_DEPENDS_research="product"
PACK_COMMANDS_research="startup kickoff deep-dive fundraise research pitch outreach content write"
PACK_RULES_research=""
PACK_SKILLS_research="brainstorm idea-validation market-research competitive-teardown deep-research investor-materials investor-outreach article-writing content-engine startup-pipeline"
PACK_AGENTS_research="idea-killer.md research-planner.md"
PACK_SCRIPTS_research=""
PACK_CLAUDE_SECTIONS_research="60-research.md"

# Helper: get pack variable by name
# Usage: pack_var "COMMANDS" "backend-micronaut" → echoes PACK_COMMANDS_backend_micronaut
pack_var() {
  local prefix="$1"
  local pack="$2"
  local safe_pack="${pack//-/_}"
  local var_name="PACK_${prefix}_${safe_pack}"
  eval echo "\${$var_name:-}"
}

# Helper: resolve dependencies (BFS)
resolve_deps() {
  local selected="$1"
  local resolved="$selected"
  local queue="$selected"
  while [[ -n "$queue" ]]; do
    local next_queue=""
    for pack in $queue; do
      local deps
      deps=$(pack_var "DEPENDS" "$pack")
      for dep in $deps; do
        case " $resolved " in
          *" $dep "*) ;;
          *) resolved="$resolved $dep"; next_queue="$next_queue $dep" ;;
        esac
      done
    done
    queue="$next_queue"
  done
  # Always include core
  case " $resolved " in
    *" core "*) ;;
    *) resolved="core $resolved" ;;
  esac
  echo "$resolved"
}
